Think of it like driving a car:
urllib (built-in) is like driving a manual transmission. You have more direct control, but you have to manage the clutch, shift gears, and worry about more details.
requests is like driving an automatic. You just press the gas and go. It handles all the complex gear-shifting for you, making the experience vastly simpler and more pleasant for 99% of your trips.

Let's Do It: The Core of requests
The most common HTTP method by far is GET. You use it every time you type a URL into your browser. It's used to retrieve, or "get," data from a server.
Let's make our very first request. We'll ask a test server for some information.
First, you'll need to install the library if you haven't already. Open your terminal or command prompt and run:
pip install requests


In [5]:
import requests
import numpy as np

response = requests.get("https://api.github.com/events")
print(response)  # this means the response is good its a green light

<Response [200]>


In [ ]:
print(f"status code:{response.status_code}")
# and to check if the ping is successfull
print(f"was the ping successfull: {response.ok}")
try:
    response.raise_for_status()
    print("No errrors were raised")
except requests.exceptions.HTTPError as err:
    print(f"an error as ouccured {err}")

status code:200
was the ping successfull: True
No errrors were raised


In [ ]:
import os
import pandas as pd

try:
    s = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
    print(f"From URL: {s}")
    df = pd.read_csv(s, header=None, encoding="utf-8")
except HTTPError:
    s = "iris.data"
    print(f"From local iris path:{s}")
    df = pd.read_csv(s, header=None, encoding="ut-8")

df.tail()


From URL: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data


0    1    2    3               4
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [ ]:
array1 = np.linspace(
    0, 1, 5
)  # creates evenly spaced numbers between 0 and 1, so here there are 5 numbers
print(array1, array1.shape)

[0.   0.25 0.5  0.75 1.  ] (5,)


what are the methods which can be used with numpy varbales
1. size - the size of the array 
2. ndim - number of dimensions like 2d matrix or 3d tensor
3. dtype - int64 or float 32
4. shape - (2,3) - the shape of this array is 2 rows and 3 columns

### these can be seen as the most fundamental methods of numpy

In [ ]:
original = np.arange(12)  # liear list
reshaped = original.reshape(3, 4)  # linear list made into 2D array of shape 3 by 4
flatten = reshaped.flatten()  # make the 2D array once again to 1D

print(original)
print(reshaped)
print(flatten)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### how to select or slice arrays

In [ ]:
# select an element from an array
element1 = reshaped[
    1, 2
]  # this will give the one in 1 row and 2nd column so this has to give us 6
# the main benefit of vectorization is you can do elementwise manipualtions fairly computationaly efficient way, that is without for loops
# what is an identity matrix
identity = np.eye(3)
identity
# then what is a diagonal matrix
diag = np.diag([1, 2, 3])
diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

radome seeds are for testing out(to make the outcomes determinstic so we can reproduce the results to test hypothesis  

In [ ]:
import random

np.random.seed(23)
uniform = np.random.random((3, 3))
uniform

array([[0.51729788, 0.9469626 , 0.76545976],
       [0.28239584, 0.22104536, 0.68622209],
       [0.1671392 , 0.39244247, 0.61805235]])

In [ ]:
normal = np.random.randn(3, 3)
normal
np.random.seed(23)
normal_int = np.random.randint(0, 10, size=(4, 3))
normal_int

array([[3, 6, 8],
       [9, 6, 8],
       [7, 9, 3],
       [6, 1, 2]])